#!/bin/bash
# Copy the PumpkinOS trap-marshalling sources the GBA build compiles into
# gba/pk/emulation, where the GBA shims for their private headers (emupalmos.h,
# m68k/*.h, logtrap.h, armemu.h) shadow the originals. Also extracts the
# 68k<->host structure encoders and the inline Sys* trap cases from emupalmos.c
# and systrap.c, which are otherwise entangled with the Musashi core.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
E=$ROOT/vendor/PumpkinOS/src/libpumpkin/emulation
D=$ROOT/gba/pk/emulation
mkdir -p "$D"
TRAPS="Mem Dm Str Tim Ctl Evt Fld Fnt Frm Lst Menu Win Snd Date Time Ftr Key Scl Pref Exg Prg Err Bmp UI Pce Sys Dlk Rct Ins Txt Crc Clipboard Category"
COMPILED=""
for t in $TRAPS; do
  if [ -f "$E/${t}SysTrap.c" ]; then cp "$E/${t}SysTrap.c" "$D/"; COMPILED="$COMPILED palmos_${t}SysTrap"; fi
done
cp "$E/sc_case.c" "$E/sc_prot.h" "$E/emupalmosinc.h" "$E/hdtrap.c" "$E/pinstrap.c" "$E/navtrap.c" "$E/emu_notif_serde.c" "$E/emu_launch_serde.c" "$E/armsyscall.c" "$D/"
# encoders/decoders: from encode_string up to the call-68K trampoline
awk '/^void encode_string\(/{p=1} /^static uint32_t call68K_func\(/{p=0} p' "$E/emupalmos.c" > "$D/encdec.inc"
# inline Sys* trap cases of palmos_systrap()
awk '/^    case sysTrapSysAppStartup: \{/{p=1} /#include "sc_case.c"/{p=0} p' "$E/systrap.c" > "$D/systrap_cases.inc"
# stubs for the per-manager trap functions we do not compile
{
  echo '/* Generated by tools/gba/sync_pumpkin.sh: trap groups the game never uses. */'
  echo '#include <stdint.h>'
  echo 'void emupalmos_panic(char *msg, int code);'
  grep -o 'palmos_[A-Za-z0-9]*SysTrap' "$E/sc_prot.h" | sort -u | while read f; do
    case " $COMPILED " in *" $f "*) ;; *)
      echo "void $f(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic(\"$f: unsupported trap\", 3); }";;
    esac
  done
} > "$D/sc_stubs.c"
echo "synced into $D"
