/* Generated by tools/gba/sync_pumpkin.sh: trap groups the game never uses. */
#include <stdint.h>
void emupalmos_panic(char *msg, int code);
void palmos_AbtSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_AbtSysTrap: unsupported trap", 3); }
void palmos_AlmSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_AlmSysTrap: unsupported trap", 3); }
void palmos_AttnSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_AttnSysTrap: unsupported trap", 3); }
void palmos_DaysSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_DaysSysTrap: unsupported trap", 3); }
void palmos_DaySysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_DaySysTrap: unsupported trap", 3); }
void palmos_EncSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_EncSysTrap: unsupported trap", 3); }
void palmos_FileSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_FileSysTrap: unsupported trap", 3); }
void palmos_FontSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_FontSysTrap: unsupported trap", 3); }
void palmos_FplSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_FplSysTrap: unsupported trap", 3); }
void palmos_GetSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_GetSysTrap: unsupported trap", 3); }
void palmos_GrfSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_GrfSysTrap: unsupported trap", 3); }
void palmos_GsiSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_GsiSysTrap: unsupported trap", 3); }
void palmos_HostSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_HostSysTrap: unsupported trap", 3); }
void palmos_HwrSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_HwrSysTrap: unsupported trap", 3); }
void palmos_LocSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_LocSysTrap: unsupported trap", 3); }
void palmos_PenSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_PenSysTrap: unsupported trap", 3); }
void palmos_PwdSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_PwdSysTrap: unsupported trap", 3); }
void palmos_ResSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_ResSysTrap: unsupported trap", 3); }
void palmos_SecSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_SecSysTrap: unsupported trap", 3); }
void palmos_SelectSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_SelectSysTrap: unsupported trap", 3); }
void palmos_SysSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_SysSysTrap: unsupported trap", 3); }
void palmos_TblSysTrap(uint32_t sp, uint16_t idx, uint32_t trap) { (void)sp; (void)idx; (void)trap; emupalmos_panic("palmos_TblSysTrap: unsupported trap", 3); }
